### ISSUE TITLE
User can register an account

### ISSUE THREAD

**Issue by codedoll** [codedoll/manga-meet#1]

**Comment by codedoll** [comment]
@JosephinaTavera  please close this user story once you are able to confirm that the registration succeeded on your part.
<img width="712" alt="screen shot 2016-07-11 at 5 55 57 pm" src="https://cloud.githubusercontent.com/assets/17578236/16748194/c0c73f5a-4790-11e6-9e81-5a30bd8df9d8.png">

**Comment by JosephinaTavera** [comment]
Registration does work if I type in the rest of the url  user/register

**Comment by JosephinaTavera** [comment]
Confirmed there is a link
